export enum Actions {
  MANAGE = 'MANAGE',
  GET_ME = 'GET_ME',
  UPDATE_ME = 'UPDATE_ME',
  REMOVE_ME = 'REMOVE_ME',
  GET_USER = 'GET_USER',
  CREATEUSER = 'CREATEUSER',
  UPDATE_USER = 'UPDATE_USER',
  GET_ALL_USERS = 'GET_ALL_USERS',
  REMOVE_USER = 'REMOVE_USER',
  GET_PRODUCTS = 'GET_PRODUCTS',
  CREATE_PRODUCT = 'CREATE_PRODUCT',
  UPDATE_PRODUCT = 'UPDATE_PRODUCT',
  DELETE_PRODUCT = 'DELETE_PRODUCT',
  CREATE_MY_PRODUCT = 'CREATE_MY_PRODUCT',
  UPDATE_MY_PRODUCT = 'UPDATE_MY_PRODUCT',
  DELETE_My_PRODUCT = 'DELETE_My_PRODUCT',
  EDIT_SECURITYGROUP = 'EDIT_SECURITYGROUP',
  SEND_EMAIL = 'SEND_EMAIL',
}

export enum Role {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  MERCHANT = 'MERCHANT',
  USER = 'USER',
}
